### ISSUE TITLE
Android Build fails "error: cannot find symbol import android.support.v4.app.NotificationCompat.WearableExtender;"

### ISSUE THREAD

**Issue by gaurav-chandra** [phonegap/phonegap-plugin-push#1270]
### Expected Behaviour
Android build should succeed

### Actual Behaviour
Android build fails

### Reproduce Scenario (including but not limited to)
The push plugin fails with "cannot find symbol"

#### Steps to Reproduce 
cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXX"
cordova build android

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 5

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Lenovo

#### Cordova CLI version and cordova platform version

    cordova --version       6.3.1                             
    cordova platform version android            5.2.2         

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.8.2

#### Sample Push Data Payload
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:20: error: cannot find symbol
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
  symbol:   class WearableExtender
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:470: error: cannot find symbol
                    NotificationCompat.Action.Builder actionBuilder =
                                             ^
  symbol:   class Builder
  location: class Action
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:471: error: cannot find symbol
                        new NotificationCompat.Action.Builder(resources.getIdentifier(action.optString(ICON, ""), DRAWABLE, packageName),
                                                     ^
  symbol:   class Builder
  location: class Action
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:489: error: method addAction in class Builder cannot be applied to given types;
                        mBuilder.addAction(wAction);
                                ^
  required: int,CharSequence,PendingIntent
  found: Action
  reason: actual and formal argument lists differ in length
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:497: error: cannot find symbol
                mBuilder.extend(new WearableExtender().addActions(wActions));
                                    ^
  symbol:   class WearableExtender
  location: class GCMIntentService
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:519: error: cannot find symbol
                if (visibility >= NotificationCompat.VISIBILITY_SECRET && visibility <= NotificationCompat.VISIBILITY_PUBLIC) {
                                                    ^
  symbol:   variable VISIBILITY_SECRET
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:519: error: cannot find symbol
                if (visibility >= NotificationCompat.VISIBILITY_SECRET && visibility <= NotificationCompat.VISIBILITY_PUBLIC) {
                                                                                                          ^
  symbol:   variable VISIBILITY_PUBLIC
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:520: error: cannot find symbol
                    mBuilder.setVisibility(visibility);
                            ^
  symbol:   method setVisibility(Integer)
  location: variable mBuilder of type Builder
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:737: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
:compileArmv7DebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.126 secs
Error: /Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:20: error: cannot find symbol
import android.support.v4.app.NotificationCompat.WearableExtender;
                                                ^
  symbol:   class WearableExtender
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:470: error: cannot find symbol
                    NotificationCompat.Action.Builder actionBuilder =
                                             ^
  symbol:   class Builder
  location: class Action
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:471: error: cannot find symbol
                        new NotificationCompat.Action.Builder(resources.getIdentifier(action.optString(ICON, ""), DRAWABLE, packageName),
                                                     ^
  symbol:   class Builder
  location: class Action
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:489: error: method addAction in class Builder cannot be applied to given types;
                        mBuilder.addAction(wAction);
                                ^
  required: int,CharSequence,PendingIntent
  found: Action
  reason: actual and formal argument lists differ in length
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:497: error: cannot find symbol
                mBuilder.extend(new WearableExtender().addActions(wActions));
                                    ^
  symbol:   class WearableExtender
  location: class GCMIntentService
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:519: error: cannot find symbol
                if (visibility >= NotificationCompat.VISIBILITY_SECRET && visibility <= NotificationCompat.VISIBILITY_PUBLIC) {
                                                    ^
  symbol:   variable VISIBILITY_SECRET
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:519: error: cannot find symbol
                if (visibility >= NotificationCompat.VISIBILITY_SECRET && visibility <= NotificationCompat.VISIBILITY_PUBLIC) {
                                                                                                          ^
  symbol:   variable VISIBILITY_PUBLIC
  location: class NotificationCompat
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:520: error: cannot find symbol
                    mBuilder.setVisibility(visibility);
                            ^
  symbol:   method setVisibility(Integer)
  location: variable mBuilder of type Builder
/Users/gauravchandra/Documents/GIT_REPOSITORIES/HealthBankApp/HealthBank/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:737: error: cannot find symbol
            mBuilder.setColor(iconColor);
                    ^
  symbol:   method setColor(int)
  location: variable mBuilder of type Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by gaurav-chandra** [comment]
I have updated all the sdk etc. with the latest versions.

**Comment by macdonst** [comment]
@gaurav-chandra you need to updated your SDK version. I know you said you did but the command line is not picking up your updates. Sometimes folks have two copies of the Android SDK's, one referenced from the command line and one from Android Studio. Make sure the two match or you CLI may (and probably is) referring to an old installation.

**Comment by gaurav-chandra** [comment]
I have the latest and android studio and cli are mapped to same sdk. I will still keep looking for solution.

![androidsdk](https://cloud.githubusercontent.com/assets/3168243/19472637/a10fc4b8-9545-11e6-82d6-a80aed14ea4e.jpg)

**Comment by gaurav-chandra** [comment]
Finally got to know what caused the problem. There was a dropbox chooser plugin, which was very old, and it had v4 jar file. It was over writing the latest updated v4 support. The older version of push plugin worked with it as it is a 1.5 yr old app.

Sorry for this issue when it was clearly not push plugin's fault.

**Comment by macdonst** [comment]
@gaurav-chandra from teh command line `echo $ANDROID_HOME` to make sure where you think the Android SDK is being picked up from is actually where you have it installed.

**Comment by gaurav-chandra** [comment]
Finally got to know what caused the problem. There was a dropbox chooser plugin, which was very old, and it had v4 jar file. It was over writing the latest updated v4 support. The older version of push plugin worked with it as it is a 1.5 yr old app. After I replaced that v4 jar with the latest one from sdk, the build went through and I got my apk file.

Sorry for this issue when it was clearly not push plugin's fault.
