### PR TITLE
Fixes #2502: iOS incompatibility with other Firebase plugins

### LINKED ISSUE #2502: iOS: Plugin installation fails when other plugin already uses Firebase
### Expected Behaviour
Install plugin without errors.

### Actual Behaviour
```
Using cordova-fetch for cordova-ios@~4.5.1
(...)
Installing "cordova-plugin-badge" for ios
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-firebase-authentication" for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-native-spinner" for ios
Installing "cordova-plugin-network-information" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-tiles" for ios
Installing "cordova-plugin-vibration" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "cordova-plugin-windows-manifest" for ios
Installing "cordova-promise-polyfill" for ios
Installing "cordova-sms-plugin" for ios
Installing "cordova-support-android-plugin" for ios
Installing "cordova-support-google-services" for ios
Installing "phonegap-plugin-multidex" for ios
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/andres/Documents/Cordova/myapp/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
Error: pod: Command failed with exit code 1
```
### Reproduce Scenario (including but not limited to)
Create app, add plugin such as [cordova-plugin-firebase-authentication](https://github.com/chemerisuk/cordova-plugin-firebase-authentication), and try to add this plugin then.
#### Cordova CLI version and cordova platform version

    cordova 7.1.0
    cordova-ios 4.5.1

#### Plugin version

    2.2.3

### PR DESCRIPTION
**Pull request by andreszs**
## Description
Changed config.xml and PushPlugin.m

## Related Issue
#2502 

## Motivation and Context
Solves plugin installation error when other plugins present use certain Firebase features already. Installation is now absolutely flawless.

## How Has This Been Tested?
Tested on iOS 11.4

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
@andreszs when I run a build with this change I run into a build error:

```
/firebase5test/platforms/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error:
      'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
#import <GoogleUtilities/GULAppEnvironmentUtil.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** ARCHIVE FAILED **
```

However, when I run it in Xcode everything compiles properly. Did you run into anything like that?

**Comment by andreszs** [comment]
@macdonst No, I didn't get such error. I'm using the [cordova-plugin-firebase-authentication](https://github.com/chemerisuk/cordova-plugin-firebase-authentication) plugin and this push plugin, and everything worked after applying these changes.

**Comment by AndreasGassmann** [comment]
Just after you submitted this PR, I tried using it together with the https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks plugin. I got a couple of build issues when using both of them together, but after removing the dynamiclinks plugin, the push plugin seemed to work.

However, now I tried to install this PR without having any other Firebase package installed, and I get a similar error:

```
/path/to/repo/platforms/ios/Pods/FirebaseCore/Firebase/Core/FIRNetwork.m:23:9: fatal error: 'GoogleToolboxForMac/GTMNSData+zlib.h' file not found
#import <GoogleToolboxForMac/GTMNSData+zlib.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** ARCHIVE FAILED **
```

**Comment by macdonst** [comment]
@AndreasGassmann ok, with that info in place I think you'll need to update your PR so that it includes two frameworks:

```
<framework src="Firebase/Core" type="podspec" spec="~> 5.0"/>
<framework src="Firebase/Messaging" type="podspec" spec="~> 5.0"/>
```

if that fixes the compile issue update the PR and let me know. I can't really test right now as I'm stuck in meetings.

**Comment by echonox** [comment]
@andreszs @macdonst Tested the plugin but silent push doesn't get received (normal push with message does) on('notification') never gets called, any suggestions?

**Comment by andreszs** [comment]
@macdonst Sorry, I **do** get the build error you mentioned eariler on `cordova build ios`, but not when adding the plugin, the platform, or building from Xcode. About your edit to **config.xml**: the build error persists, I tried several combinations of settings in config.xml and the result is the same: command line build will fail.

@echonox I had that error with silent push notifications too. If you add the `content_available = true` parameter to your **FCM push payload**, it will be processed normally. Don't ask me why, but it works fine with iOS 11.4 and 12.

**As a side note:** chemerisuk, the [cordova-plugin-firebase-authentication](https://github.com/chemerisuk/cordova-plugin-firebase-authentication) author, also [pointed out](https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/35) that when using his plugin **CLI build will fail**. So far I couldn't find any solution for this.

The only way to overcome this issue, whenever you make **changes to www** content follow these steps:
- close Xcode
- `cordova prepare ios`  - _no errors here :)_
- `pod update` in platforms/ios - _or could be pod install instead, I prefer update_
- open your .xcworkspace with Xcode, build and deploy normally.

**To add, remove, change or update a plugin**:
- close Xcode
- `cordova platform remove ios`
- add, remove, update plugins normally
- `cordova platform add ios`
- `pod update` in platforms/ios
- open your .xcworkspace with Xcode
- select your dev team
- perform other first-time Xcode tweaks as needed (like adding _URL type_ if you use Auth plugin)

The previous steps work perfectly fine with **Xcode 9** and **Cordova 7.1.0**.

**Review by seamlink-aalves — APPROVED** [review]
