### ISSUE TITLE
Build fails using v1.4.2

### ISSUE THREAD

**Issue by TheMattRay** [phonegap/phonegap-plugin-push#340]
Works fine using v1.3.0 but when I upgraded to 1.4.2 it fails.

Environment:
```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.8.8
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.1.1 Build version 7B1005
```

Console log:

```
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:22: error: cannot find symbol
import com.google.android.gms.gcm.GcmListenerService;
                                 ^
  symbol:   class GcmListenerService
  location: package com.google.android.gms.gcm
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:38: error: cannot find symbol
public class GCMIntentService extends GcmListenerService implements PushConstants {
                                      ^
  symbol: class GcmListenerService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:7: error: package com.google.android.gms.iid does not exist
import com.google.android.gms.iid.InstanceID;
                                 ^
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:8: error: package com.google.android.gms.iid does not exist
import com.google.android.gms.iid.InstanceIDListenerService;
                                 ^
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:14: error: cannot find symbol
public class PushInstanceIDListenerService extends InstanceIDListenerService implements PushConstants {
                                                   ^
  symbol: class InstanceIDListenerService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:9: error: package com.google.android.gms.iid does not exist
import com.google.android.gms.iid.InstanceID;
                                 ^
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:63: error: cannot find symbol
            SharedPreferences prefs = getApplicationContext().getSharedPreferences(PushPlugin.COM_ADOBE_PHONEGAP_PUSH, Context.MODE_PRIVATE);
                                      ^
  symbol:   method getApplicationContext()
  location: class GCMIntentService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:79: error: cannot find symbol
                showNotificationIfPossible(getApplicationContext(), extras);
                                           ^
  symbol:   method getApplicationContext()
  location: class GCMIntentService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:86: error: cannot find symbol
                showNotificationIfPossible(getApplicationContext(), extras);
                                           ^
  symbol:   method getApplicationContext()
  location: class GCMIntentService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:57: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:203: error: cannot find symbol
        NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                                                                         ^
  symbol:   method getSystemService(String)
  location: class GCMIntentService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:204: error: method getAppName in class GCMIntentService cannot be applied to given types;
        String appName = getAppName(this);
                         ^
  required: Context
  found: GCMIntentService
  reason: actual argument GCMIntentService cannot be converted to Context by method invocation conversion
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:209: error: no suitable constructor found for Intent(GCMIntentService,Class<PushHandlerActivity>)
        Intent notificationIntent = new Intent(this, PushHandlerActivity.class);
                                    ^
    constructor Intent.Intent(String,Uri,Context,Class<?>) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent(Context,Class<?>) is not applicable
      (actual argument GCMIntentService cannot be converted to Context by method invocation conversion)
    constructor Intent.Intent(String,Uri) is not applicable
      (actual argument GCMIntentService cannot be converted to String by method invocation conversion)
    constructor Intent.Intent(String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent(Intent) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent() is not applicable
      (actual and formal argument lists differ in length)
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:215: error: no suitable method found for getActivity(GCMIntentService,int,Intent,int)
        PendingIntent contentIntent = PendingIntent.getActivity(this, requestCode, notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
                                                   ^
    method PendingIntent.getActivity(Context,int,Intent,int,Bundle) is not applicable
      (actual and formal argument lists differ in length)
    method PendingIntent.getActivity(Context,int,Intent,int) is not applicable
      (actual argument GCMIntentService cannot be converted to Context by method invocation conversion)
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:323: error: no suitable constructor found for Intent(GCMIntentService,Class<PushHandlerActivity>)
                    Intent intent = new Intent(this, PushHandlerActivity.class);
                                    ^
    constructor Intent.Intent(String,Uri,Context,Class<?>) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent(Context,Class<?>) is not applicable
      (actual argument GCMIntentService cannot be converted to Context by method invocation conversion)
    constructor Intent.Intent(String,Uri) is not applicable
      (actual argument GCMIntentService cannot be converted to String by method invocation conversion)
    constructor Intent.Intent(String) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent(Intent) is not applicable
      (actual and formal argument lists differ in length)
    constructor Intent.Intent() is not applicable
      (actual and formal argument lists differ in length)
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:326: error: no suitable method found for getActivity(GCMIntentService,int,Intent,int)
                    PendingIntent pIntent = PendingIntent.getActivity(this, i, intent, PendingIntent.FLAG_UPDATE_CURRENT);
                                                         ^
    method PendingIntent.getActivity(Context,int,Intent,int,Bundle) is not applicable
      (actual and formal argument lists differ in length)
    method PendingIntent.getActivity(Context,int,Intent,int) is not applicable
      (actual argument GCMIntentService cannot be converted to Context by method invocation conversion)
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:495: error: cannot find symbol
                AssetManager assetManager = getAssets();
                                            ^
  symbol:   method getAssets()
  location: class GCMIntentService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:19: error: cannot find symbol
        SharedPreferences sharedPref = getApplicationContext().getSharedPreferences(COM_ADOBE_PHONEGAP_PUSH, Context.MODE_PRIVATE);
                                       ^
  symbol:   method getApplicationContext()
  location: class PushInstanceIDListenerService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:23: error: cannot find symbol
                String token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
                                                      ^
  symbol:   method getApplicationContext()
  location: class PushInstanceIDListenerService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushInstanceIDListenerService.java:23: error: cannot find symbol
                String token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
                               ^
  symbol:   variable InstanceID
  location: class PushInstanceIDListenerService
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:72: error: cannot find symbol
                            token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
                                    ^
  symbol: variable InstanceID
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:76: error: cannot find symbol
                            token = InstanceID.getInstance(getApplicationContext()).getToken(senderID, GCM);
                                    ^
  symbol: variable InstanceID
/Users/themattray/Documents/Code/alligator/platforms/android/src/com/adobe/phonegap/push/PushPlugin.java:132: error: cannot find symbol
                        InstanceID.getInstance(getApplicationContext()).deleteInstanceID();
                        ^
  symbol: variable InstanceID
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
23 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.344 secs

/Users/themattray/Documents/code/alligator/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Users/themattray/Documents/code/alligator/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/themattray/Documents/code/alligator/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/themattray/Documents/code/alligator/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/themattray/Documents/code/alligator/platforms/android/cordova/build: Command failed with exit code 1
```

**Comment by macdonst** [comment]
@TheMattRay it looks like you are missing Google Play Services. Check out the instructions on compiling here:

https://github.com/phonegap/phonegap-plugin-push#compiling

**Comment by macdonst** [comment]
@TheMattRay I'm closing this as no response in 3 weeks. I hope your issue has been resolved.
