### ISSUE TITLE
Send to GCM Topic on iOS not received

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-push#440]
The iOS implementation allows you to subscribe to topics but when you send to the topic the message is not received.

**Comment by jesercm** [comment]
I've tested on android and ios. Android works everything just fine. On iOs a receive the registration id but can't send a push notification, invalid registration.

**Comment by macdonst** [comment]
@jesercm what does your registration ID look like?

**Comment by jesercm** [comment]
Looks like this: 
2a32c0b52e3b5bec6b9288d3369f7c856b0203260c232f7c5f4c8c70ba921a89

**Comment by macdonst** [comment]
@jesercm and you get that from the registration event? Can I see the parameters you pass to init?

**Comment by jesercm** [comment]
var push = PushNotification.init({
	    android: {
	        senderID: "787565994296"
	    },
	    ios: {
	        alert: "true",
	        badge: "true",
	        sound: "true"
	    },
	    windows: {}
	});

	push.on('registration', function(data) {
		alert(data.registrationId);
	    // data.registrationId
	});

	push.on('notification', function(data) {
		alert('NOTIFICATION: ' + data.message);
	    // data.message,
	    // data.title,
	    // data.count,
	    // data.sound,
	    // data.image,
	    // data.additionalData
	});

	push.on('error', function(e) {
		alert('ERROR: ' + e.message);
	    // e.message
	});

**Comment by macdonst** [comment]
@jesercm you are not using GCM on iOS. You are missing a couple of parameters in your init method. Look at `senderId` and `gcmSandbox` at https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#ios

Also, once you get the proper registration ID you still won't be able to receive topic messages. Just regular pushes to the reg ID.

**Comment by jesercm** [comment]
@macdonst I have added the senderID on ios, then i get another registration ID, just like i get on android. But still cant receive messages. What you mean with regular pushes and topic messages?

**Comment by glecaros** [comment]
Hi, it seems that this is caused by the branch with the topic code (https://github.com/phonegap/phonegap-plugin-push/tree/issue79) not being merged into master. I tried that in my local repo and notifications are working fine.

**Comment by bardu** [comment]
@macdonst I have the same issue here. Everything looks fine, node-gcm sender.send() response with message_id, but on.('notification') never fires on iOS.

Can we expect a merge as @glecaros suggested? Thanks.

**Comment by macdonst** [comment]
@bardu it has nothing to do with the branch @glecaros mentioned. That is to fix the issue where topic messages are not received by GCM iOS.

Please make sure you do the following:

1) Upload your iOS certs to GCM service so google can forward your pushes to APNS.
2) You set senderId and gcmSandbox correctly in your iOS options.
3) You receive a registration ID in the formation "XXXXX:YYYYY". Having the `:` in the registration ID means you've connected with Google.

**Comment by bardu** [comment]
@macdonst Thanks for your response.

I have this all in place and get the registration id in required format. And node-gcm sender.send() response is:

> Push success: {"message_id":7157765217199290000}

However, on('notification',..) is not firing. All works fine with Android.

Just can think off my options, if you could have a look:

```js
var topics = _getTopics();
        var push = PushNotification.init({
            android: {
                senderID: app.config.gcm.senderID,
                topics: topics
            },
            ios: {
                senderID: app.config.gcm.senderID,
                gcmSandbox: "true",
                alert: "true",
                badge: "true",
                sound: "true",
                vibration: "true",
                topics: topics
            }
        });
```

**Comment by macdonst** [comment]
@bardu right GCM topic messages on iOS are not working currently.

**Comment by bardu** [comment]
Well, that brings me back to my original question:
>Can we expect a merge as @glecaros suggested? Thanks.

**Comment by macdonst** [comment]
@bardu well I can do the merge of that branch but I've never successfully received a topic notification on iOS running that code so I'd like to look into it some more.

**Comment by bardu** [comment]
@macdonst makes sense, has this bug a high priority for you? Right now it is quite a showstopper for our app.

**Comment by jesercm** [comment]
My code uses:
 var push = PushNotification.init({
            android: {
                senderID: mysenderID,
            },
            ios: {
                senderID: mysenderID,
                gcmSandbox: "true",
                alert: "true",
                badge: "true",
                sound: "true",
                vibration: "true",
            }
        });

This should work for both Android and iOS sending a simple message? On my tests this works for Android.

When i run my app on iOS i get a registration ID just like the same format on android, but when i try to send the push notification, only on Android is sent. I get Invalid Registration. I double checked the registration id that i get from iOS but nothing changes.

**Comment by macdonst** [comment]
@bardu this is an open source project so is you pull from the `issue79` branch and test to see if it works for you that would help greatly. Currently, I'm working on something exciting to do with push so I've got no ETA when I'll be able to get to this issue.

@jesercm did you upload your APNS certs to your Google project?

**Comment by jesercm** [comment]
@macdonst Where do i upload the certs?

**Comment by macdonst** [comment]
@jesercm https://developers.google.com/mobile/add?platform=ios&cntapi=gcm&cnturl=https:%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fios%2Fclient&cntlbl=Continue%20Adding%20GCM%20Support&%3Fconfigured%3Dtrue

**Comment by bardu** [comment]
@macdonst I pulled from issue79 branch and can confirm that the notification is send to iOS devices (iPhone 6 iOS v9.2, iPhone 5 iOS v9.1) however there is no sound, vibration and badge.

**Comment by macdonst** [comment]
@bardu so you send a push to a GCM topic and it gets to your iOS device?

**Comment by bardu** [comment]
@macdonst yes

**Comment by bardu** [comment]
@macdonst There is another issue: While on Android the device receives the notification ones, on iOS multiple times.

Hope this console output from iOS can offer some hints:
>2016-01-07 10:34:34.594: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion
2016-01-07 10:34:37.141: GGLInstanceID | Invalid last checkin timestamp in future.
2016-01-07 10:34:37.142 YukonNow[1728:739596] Checkin successful with authId: -omitted-, digest: -omitted-, lastCheckinTimestamp: 1452191677000
2016-01-07 10:34:37.178 YukonNow[1728:739596] GCM Registration Token: -omitted-
2016-01-07 10:34:37.180 YukonNow[1728:739596] subscribe from topic: accommodation
2016-01-07 10:34:37.184 YukonNow[1728:739596] subscribe from topic: arts
2016-01-07 10:34:37.186 YukonNow[1728:739596] subscribe from topic: auto
2016-01-07 10:34:37.187 YukonNow[1728:739596] subscribe from topic: beauty
2016-01-07 10:34:37.189 YukonNow[1728:739596] subscribe from topic: coffee
2016-01-07 10:34:37.190 YukonNow[1728:739596] subscribe from topic: clothing
2016-01-07 10:34:37.192 YukonNow[1728:739596] subscribe from topic: eatery
2016-01-07 10:34:37.193 YukonNow[1728:739596] subscribe from topic: wellness
2016-01-07 10:34:37.194 YukonNow[1728:739596] subscribe from topic: entertainment
2016-01-07 10:34:37.196 YukonNow[1728:739596] subscribe from topic: gov
2016-01-07 10:34:37.197 YukonNow[1728:739596] subscribe from topic: municipal
2016-01-07 10:34:37.200 YukonNow[1728:739596] subscribe from topic: outdoor
2016-01-07 10:34:37.202 YukonNow[1728:739596] subscribe from topic: sports
2016-01-07 10:34:37.205 YukonNow[1728:739596] subscribe from topic: trafic
2016-01-07 10:34:37.206 YukonNow[1728:739596] subscribe from topic: transportation
2016-01-07 10:34:37.208 YukonNow[1728:739596] subscribe from topic: wildlife
2016-01-07 10:34:37.258 YukonNow[1728:739596] Already subscribed to accommodation
2016-01-07 10:34:37.259 YukonNow[1728:739596] Already subscribed to arts
2016-01-07 10:34:37.261 YukonNow[1728:739596] Already subscribed to auto
2016-01-07 10:34:37.262 YukonNow[1728:739596] Already subscribed to beauty
2016-01-07 10:34:37.263 YukonNow[1728:739596] Already subscribed to coffee
2016-01-07 10:34:37.272 YukonNow[1728:739596] Already subscribed to clothing
2016-01-07 10:34:37.275 YukonNow[1728:739596] Already subscribed to eatery
2016-01-07 10:34:37.276 YukonNow[1728:739596] Already subscribed to wellness
2016-01-07 10:34:37.278 YukonNow[1728:739596] Already subscribed to entertainment
2016-01-07 10:34:37.279 YukonNow[1728:739596] Already subscribed to gov
2016-01-07 10:34:37.285 YukonNow[1728:739596] Already subscribed to municipal
2016-01-07 10:34:37.285 YukonNow[1728:739596] Already subscribed to outdoor
2016-01-07 10:34:37.286 YukonNow[1728:739596] Already subscribed to sports
2016-01-07 10:34:37.287 YukonNow[1728:739596] Already subscribed to trafic
2016-01-07 10:34:37.288 YukonNow[1728:739596] Already subscribed to transportation
2016-01-07 10:34:37.288 YukonNow[1728:739596] Already subscribed to wildlife
2016-01-07 10:34:40.160 YukonNow[1728:739596] active
2016-01-07 10:34:40.160 YukonNow[1728:739596] PushPlugin skip clear badge
2016-01-07 10:35:39.579 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.580 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.581 YukonNow[1728:739596] this should be a silent push
82 YukonNow[1728:739596] Notification received
2016-01-07 10:35:39.582 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.582 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.606 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:39.680 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.689 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.691 YukonNow[1728:739596] this should be a silent push
91 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:39.691 YukonNow[1728:739596] Notification received
6-01-07 10:35:39.691 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.692 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.693 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:39.775 YukonNow[1728:739596] THREAD WARNING: ['PushNotification'] took '81.431152' ms. Plugin should use a background thread.
2016-01-07 10:35:39.803 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.805 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.805 YukonNow[1728:739596] this should be a silent push
2016-01-07 10:35:39.823 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:39.825 YukonNow[1728:739596] Notification received
2016-01-07 10:35:39.827 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.828 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.837 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:39.841 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.856 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.858 YukonNow[1728:739596] this should be a silent push
2016-01-07 10:35:39.859 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:39.861 YukonNow[1728:739596] Notification received
2016-01-07 10:35:39.863 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.867 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.871 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:39.873 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.874 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.874 YukonNow[1728:739596] this should be a silent push
2016-01-07 10:35:39.875 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:39.876 YukonNow[1728:739596] Notification received
2016-01-07 10:35:39.878 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.879 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.880 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:39.942 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:39.954 YukonNow[1728:739596] app in-active
2016-01-07 10:35:39.955 YukonNow[1728:739596] this should be a silent push
2016-01-07 10:35:39.955 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:39.957 YukonNow[1728:739596] Notification received
2016-01-07 10:35:39.958 YukonNow[1728:739596] Push Plugin key: content-available
2016-01-07 10:35:39.959 YukonNow[1728:739596] Push Plugin key: alert
2016-01-07 10:35:39.976 YukonNow[1728:739596] Push Plugin finish called
2016-01-07 10:35:41.277 YukonNow[1728:739596] didReceiveNotification with fetchCompletionHandler
2016-01-07 10:35:41.277 YukonNow[1728:739596] app in-active
2016-01-07 10:35:41.277 YukonNow[1728:739596] this should be a silent push
77 YukonNow[1728:739596] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
2016-01-07 10:35:41.278 YukonNow[1728:739596] Notification received
...

**Comment by jesercm** [comment]
@macdonst I did have uploaded the p12 files. Do i need to use GoogleService-Info.plist for something?

**Comment by bardu** [comment]
@macdonst Please ignore my last post. The multiple notifications sent to iOS was a bug on my app server.

@jesercm Yes, you need to drag and drop it into your cordova project. I usually put it into
myproject/platforms/ios/myproject folder.

Then open Xcode by double clicking .xcworkspace.

in Xcode Project Build Phases
	--> Copy Bundle Resources click + and
			--> Add other
					--> select GoogleServiceInfo.plist

in Xcode Build Settings (only if build error: Undefined symbols for architecture arm64:)
	--> Linking
			--> Other Linker Flags
					--> Debug
						--> add $(inherited) 

From here on the project should build in Xcode.

If you get a build error in Codova CLI such as error: Ld build/device/YourProject.app/YourProject normal armv7 
checkout my solution at https://github.com/phonegap/phonegap-plugin-push/issues/456

**Comment by jesercm** [comment]
@bardu There is a way to use it on Phonegap Build?

**Comment by bardu** [comment]
@jesercm it builds with Cordova,  but you have to do the steps in Xcode. I don't use Phonegap Build.

**Comment by jesercm** [comment]
@bardu @macdonst  If anyone knows how to put the data og GoogleService-Info.plist into config.xml, please let me know. Thanks

**Comment by macdonst** [comment]
@bardu that's what I'm working on. Automatically adding the info in GoogleService-Info.plist into the project when you add the plugin.

**Comment by bardu** [comment]
@macdonst Did you have a chance to test issue79 branch again? It works for me on iPhone5, 6, except sound, vibration, badge but this branch is 18 commits behind master.

**Comment by bardu** [comment]
>@bardu that's what I'm working on. Automatically adding the info in GoogleService-Info.plist into the project when you add the plugin.

Awesome! Would make life much easier.

**Comment by macdonst** [comment]
@bardu can you pull the code from `issue79` again and add it locally to your project? When you do the CLI will look like:

`cordova plugin add ../phonegap-plugin-push --variable SENDER_ID="XXXX" --variable GOOGLE_APP_ID="YYYY"`

Where the XXXX is your GCM_SENDER_ID and YYYY is the GOOGLE_APP_ID from the GoogleService-Info.plist.

Also, please make sure that the plist is not in your project anymore.

**Comment by jesercm** [comment]
@macdonst This means that we will be able to use something like below when merged into master for PGB?

<plugin name="phonegap-plugin-push">
	<param name="SENDER_ID" value="xxxx" />
	<param name="GOOGLE_APP_ID" value="yyyy" />
</plugin>

**Comment by jesercm** [comment]
<plugin name="phonegap-plugin-push">
	<param name="SENDER_ID" value="xxxx" />
	<param name="GOOGLE_APP_ID" value="yyyy" />
</plugin>

**Comment by macdonst** [comment]
@jesercm correct!

**Comment by jesercm** [comment]
@macdonst  That is awesome. Congrats for this!

**Comment by macdonst** [comment]
@jesercm don't congratulate me yet. I'm not 100% sure that it works :smiley:

**Comment by jesercm** [comment]
@macdonst The iniciative works :smile:

**Comment by macdonst** [comment]
What?

**Comment by jesercm** [comment]
@macdonst Your iniciative to make this plugin, its good.

**Comment by bardu** [comment]
@macdonst Just want to let you know that I'm testing code from issue79, however, I run into some issues and try to figure out the root. Will response again later the day.

**Comment by bardu** [comment]
@macdonst Here is what I have done so far and the issues:
(platform iOS v.3.9.2)

> 1. double clicked myProject.xcworkspace to open the project in Xcode and removed references to GoogleService-Info.plist
2. cordova plugin rm phonegap-plugin-push  (was issue79 version 1.4.x)
3. cordova plugin add ../phonegap-plugin-push --variable SENDER_ID="XXXX" --variable (from issue79 branch) GOOGLE_APP_ID="YYYY" (Where the XXXX is your GCM_SENDER_ID and YYYY is the GOOGLE_APP_ID from the GoogleService-Info.plist.)
4. cordova run ios --device

Sending GCM topics to iOS works on my iPhone 6, 5 both with iOS 9.2, however, there are no sound, vibration and badge.

Now, I updated iOS platform to latest version
> cordova platform update ios@4.0.1

and get the following build error:

> /Users/bardu/c9sdk/cordova-projects/yn/platforms/ios/YukonNow/Classes/MainViewController.m:109:19: error: no visible @interface for 'CDVViewController' declares the selector 'webViewDidFinishLoad:'
    return [super webViewDidFinishLoad:theWebView];
            ~~~~~ ^~~~~~~~~~~~~~~~~~~~
1 error generated.

and 

> The following build commands failed:
        CompileC build/YukonNow.build/Debug-iphoneos/YukonNow.build/Objects-normal/armv7/MainViewController.o YukonNow/Classes/MainViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I have an issue on Android too, but need to go on a Linux box since my iMac doesn't recognize my Samsung S6. Later more.

**Comment by fredgalvao** [comment]
That first issue on iOS compilation is caused by a known cordova-ios issue, nothing related to this plugin. See [here](https://issues.apache.org/jira/browse/CB-9254) for details.
tl:dr; you need to `cordova platform rm ios && cordova platform add ios`, with all the fun stuff involved.

**Comment by bardu** [comment]
@fredgalvao Thanks. Just reverted to 3.9.2 to focus on the plugin.

@macdonst So, as I mentioned earlier works for me on iOS but  there is no sound, vibration and badge.

The Android issue I mentioned above was not related to this plugin.

**Comment by macdonst** [comment]
@bardu so just to confirm, when you use the `issue79` branch you are able to receive messages that are sent to GCM topics on iOS?

**Comment by bardu** [comment]
@macdonst yes, I do.

**Comment by macdonst** [comment]
@bardu awesome, I'll merge this into master soonish.

**Comment by denisbabineau** [comment]
@macdonst I can confirm that issue79 branch (merged in 1.5.3 in my fork) fixes this for me as well, +1 great work!

Probably not valuable now but I could not see the registered topic in the iid prior to the merge, but evidently it was present when working, after the merge. (when querying https://iid.googleapis.com/iid/info/<id>?&details=true)

**Comment by bardu** [comment]
> @bardu awesome, I'll merge this into master soonish. 

@macdonst Was this ever merged?

**Comment by macdonst** [comment]
@bardu yes, it's in master now.

**Comment by Gnaneshwar511** [comment]
I'm still not receiving it on IOS when I'm using topics array. I'm getting the notification if I'm sending it with device id.
Can someone please tell me what the problem is? I've used the following payload:
{
    "to" : "/topics/general",
    "notification" : {
"body" : "great match!",
"title" : "Portugal vs. Denmark",
"icon" : "myicon"
},
    "data" : {
      "url" : "www.url.loc"
    }
  }

**and my js code is:**
ios: {
senderID: xxxxxxx,
priority: "high",
alert: "true",
badge: "true",
sound: "true",
gcmSandbox: "true",
topics: ['general']
}

I also have this feeling that I'm not using the version of code with the merged branch related to issue79 (Though I do not know how to confirm it)

**Comment by santhoshscs** [comment]
@Gnaneshwar511 - I was trying with an  app i had created with the step by step from [http://macdonst.github.io/push-workshop/] (this was not covering ios)

I also had a similar issue where I was getting topic notifications correctly in Android but Not in Ios . When I send notificatinos to direct Device Id's from FCM console as well as POST (with PostMan Chrome Plugin) - I was getting these notifications delivered suceesfully
In the end the isssue was the wrong version of the plugin I used
I solved the issue by 

```
1. cordova plugin rm phonegap-plugin-push --save
2. cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXX" --variable GOOGLE_APP_ID="XXXX" --save
3. cordova run ios --device
```

(GOOGLE_APP_ID - I copied from GoogleService-Info.plist downloaded from FCM console)

**Comment by Lestt** [comment]
Hi guys,

I'am the same issue on iOs(everything is ok on Android). I'am using the latest version (1.9.0) on the master branch.
I added my plugin with this command (using ionic):
```
ionic add plugin phonegap-plugin-push --variable SENDER_ID="XXXXXX" --variable GOOGLE_APP_ID="XXXX" --save
```
First i didn't set the GOOGLE_APP_ID (didn't find anything in the doc about it, maybe i missed it).
All my certificates are ok, i'm gonna check another time but everything seems to be good.
@macdonst can you confirm that we don't need to add the GoogleService-Info.plist, it's done automatically ?
Is this issue is closed and committed on master ?
Thanks for the help !
